name: waterwatch
channels:
 - conda-forge
 - base
 - bioconda
 - R
dependencies:
 - r-base
 - r-tidyverse
 - r-gganimate
 - r-plotly
 - r-rmarkdown
 - wget
 - snakemake
 - graphviz
 - coreutils>=9.1
 
